monolog:
    handlers:
        main:
            type: stream
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
            buffer_size: 0
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            bubble: false
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
